config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  
  get 'profil', to: 'users#show', as: 'my_profil'
  
  get 'items/:id', to: 'items#show', as: 'item'
  
  post 'cart/add/:id', to: 'carts#add_to_cart', as: 'add_item_to_cart'
  post 'cart/delete/:id', to: 'carts#delete_of_cart', as: 'delete_item_of_cart'
  post 'cart/payment', to: 'carts#payment', as: 'cart_payment'
  post 'merci', to: 'orders#merci', as: 'merci'
  get 'cart', to: 'carts#show', as: 'cart_list'

  # get 'users/edit', to: 'users#edit', as: 'user_edit'

  post 'order/add/:id', to: 'orders#add_to_order', as: 'add_cart_to_order'
  post 'order/delete/:id', to: 'orders#delete_order', as: 'delete_order'
  get 'orders/new', to: 'orders#new', as: 'new_order'
  get 'orders/:id', to: 'orders#show', as: 'order'










  # edit_user_registration_path 	GET 	/users/edit(.:format) 	

  resources :orders
  resources :carts

  devise_for :users , except: [:edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :firstname, :name, presence: true, format: { with: /\A[-a-zA-Z]*\z/ }

  has_one :cart
  has_many :added_items, through: :cart

  has_many :orders
  has_many :purchased_items, through: :orders

  after_create :create_account

  def create_account
    user = User.last
    cart = Cart.new
    user.cart = cart
    user.save
    cart.save
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user! 
  def show
  	@orders = current_user.orders
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<meta name="robots" content="index, follow">
<meta name="description" content="Boomerang is a responsive website template based on the well known Bootstrap framework. It's very well structured with lots of features and demos ready to be used.">
<meta name="keywords" content="bootstrap, responsive, template, website, html, theme, ux, ui, web, design, developer, support, business, corporate, real estate, education, medical, school, education, demo, css, framework">
<meta name="author" content="Webpixels">

<title>Boomerang - Multipurpose Bootstrap Theme</title>

<!-- Bootstrap -->
<link rel="stylesheet" href="../../assets/vendor/bootstrap/css/bootstrap.min.css" type="text/css">

<!-- Fonts -->
<link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700,800|Roboto:400,500,700" rel="stylesheet"> 

<!-- Plugins -->
<link rel="stylesheet" href="../../assets/vendor/swiper/css/swiper.min.css">
<link rel="stylesheet" href="../../assets/vendor/hamburgers/hamburgers.min.css" type="text/css">
<link rel="stylesheet" href="../../assets/vendor/animate/animate.min.css" type="text/css">
<link rel="stylesheet" href="../../assets/vendor/fancybox/css/jquery.fancybox.min.css">

<!-- Icons -->
<link rel="stylesheet" href="../../assets/fonts/font-awesome/css/font-awesome.min.css" type="text/css">
<link rel="stylesheet" href="../../assets/fonts/ionicons/css/ionicons.min.css" type="text/css">
<link rel="stylesheet" href="../../assets/fonts/line-icons/line-icons.css" type="text/css">
<link rel="stylesheet" href="../../assets/fonts/line-icons-pro/line-icons-pro.css" type="text/css">

<!-- Linea Icons -->
<link rel="stylesheet" href="../../assets/fonts/linea/arrows/linea-icons.css" type="text/css">
<link rel="stylesheet" href="../../assets/fonts/linea/basic/linea-icons.css" type="text/css">
<link rel="stylesheet" href="../../assets/fonts/linea/ecommerce/linea-icons.css" type="text/css">
<link rel="stylesheet" href="../../assets/fonts/linea/software/linea-icons.css" type="text/css">

<!-- Global style (main) -->
<link id="stylesheet" type="text/css" href="../../assets/css/boomerang.min.css" rel="stylesheet" media="screen">

<!-- Custom style - Remove if not necessary -->
<link type="text/css" href="../../assets/css/custom-style.css" rel="stylesheet">

<!-- Favicon -->
<link href="../../assets/images/favicon.png" rel="icon" type="image/png">


</head>
<body>


<!-- MAIN WRAPPER -->
<div class="body-wrap" data-template-mode="cards">
    <div id="st-container" class="st-container">

        <nav class="st-menu st-effect-1" id="menu-1">
    <div class="st-profile">
        <div class="st-profile-user-wrapper">
            <div class="profile-user-image">
                <img src="../../assets/images/prv/people/person-1.jpg" class="img-circle" />
            </div>
            <div class="profile-user-info">
                <span class="profile-user-name">User_current</span>
                <span class="profile-user-email">username@example.com</span>
            </div>
        </div>
    </div>

    <div class="st-menu-list mt-2">
        <ul>
            <li>
                <a href="#">
                    <i class="ion-ios-bookmarks-outline"></i> Theme documentation
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="ion-ios-cart-outline"></i> Purchase Tribus
                </a>
            </li>
        </ul>
    </div>

    <h3 class="st-menu-title">Account</h3>
    <div class="st-menu-list">
        <ul>
            <li>
                <a href="#">
                    <i class="ion-ios-person-outline"></i> User profile
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="ion-ios-location-outline"></i> My addresses
                </a>
            </li>
            <li>

            <li>
                <a href="#">
                    <i class="ion-ios-unlocked-outline"></i> Password update
                </a>
            </li>
        </ul>
    </div>

    <h3 class="st-menu-title">Support center</h3>
    <div class="st-menu-list">
        <ul>
            <li>
                <a href="#">
                    <i class="ion-ios-information-outline"></i> About Tribus
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="ion-ios-email-outline"></i> Contact &amp; support
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-camera"></i> Getting started
                </a>
            </li>
        </ul>
    </div>
</nav>


    
                    <section class="slice-sm sct-color-1">
                        <div class="profile">
                            <div class="container">
                                <div class="row cols-xs-space cols-sm-space cols-md-space">
                                    <div class="col-lg-4">
                                        <div class="sidebar sidebar--style-2 no-border stickyfill">
                                                <div class="widget">
        <!-- Profile picture -->
        <div class="profile-picture profile-picture--style-2">
            <img src="https://lh3.googleusercontent.com/-vS2Whp_bOi4/WufGwbrVtRI/AAAAAAAF-_A/PjJDMj5pij8JPND6inftluNx5_1NWkLPgCJoC/w530-h680-n/.facebook_1525139094268.jpg" class="img-center">
        </div>

        <!-- Profile details -->
        <div class="profile-details">
            <h2 class="heading heading-4 strong-500 profile-name"> <%= current_user.firstname + " " + current_user.name %></h2>
            <h3 class="heading heading-light heading-6 strong-400 profile-location">Anywhere</h3>
        </div>

        <!-- Profile connect -->
        <div class="profile-connect mt-4">
            <a href="<%= edit_user_registration_path %>" class="btn btn-styled btn-block btn-rounded btn-base-1">Edit</a>
        </div>

        <!-- Profile stats -->
        <div class="profile-stats clearfix">
            <div class="stats-entry">
                <span class="stats-count">180</span>
                <span class="stats-label text-uppercase">Projects</span>
            </div>
            <div class="stats-entry">
                <span class="stats-count">1.3K</span>
                <span class="stats-label text-uppercase">Followers</span>
            </div>
        </div>
    </div>
                                        </div>
                                    </div>

                                    <div class="col-lg-8">
                                        <div class="main-content">
                                            <!-- Page title -->
                                            <div class="page-title">
                                                <div class="row align-items-center">
                                                    <div class="col-lg-6 col-12">
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="link-menu link-menu--style-3 py-4 border-bottom">
                                                <a href="<%= edit_user_registration_path %>">Edit informations</a>
                                            </div>

                                            <!-- Order history table -->
                                            <div class="card no-border">
                                            <% if @orders.length > 0 %>
                                                <div>
                                                    <table class="table table-sm table-hover">
                                                        <thead>
                                                            <tr>
                                                                <th>Order</th>
                                                                <th>Amount</th>
                                                                <th>Link</th>
                                                            </tr>
                                                        </thead>

                                                        <tbody>
                                                            <% @orders.each do |order| %>
                                                            <tr>
                                                                <td>
                                                                    <a href="<%=order_path(order.id)%>"><%=order.id%></a>
                                                                </td>
                                                                <td> <%= order.price_total %></td>
                                                                <td>
                                                                    <a href="<%=order_path(order.id)%>">link</a>
                                                                </td>
                                                                
                                                            </tr>
                                                            <% end %>
                                                        </tbody>
                                                    </table>
                                                </div>
                                            <% else %>
                                                <div> 
                                                    Il n'y a pas encore de commande ? Mais qu'attends-tu ? 
                                                </div>
                                            <% end %>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>

                    
                </div>
            </div>
        </div><!-- END: st-pusher -->
    </div><!-- END: st-container -->
</div><!-- END: body-wrap -->

<!-- SCRIPTS -->
<a href="#" class="back-to-top btn-back-to-top"></a>

<!-- Core -->
<script src="../../assets/vendor/jquery/jquery.min.js"></script>
<script src="../../assets/vendor/popper/popper.min.js"></script>
<script src="../../assets/vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="../../assets/js/slidebar/slidebar.js"></script>
<script src="../../assets/js/classie.js"></script>

<!-- Bootstrap Extensions -->
<script src="../../assets/vendor/bootstrap-notify/bootstrap-growl.min.js"></script>
<script src="../../assets/vendor/scrollpos-styler/scrollpos-styler.js"></script>

<!-- Plugins: Sorted A-Z -->
<script src="../../assets/vendor/adaptive-backgrounds/adaptive-backgrounds.js"></script>
<script src="../../assets/vendor/countdown/js/jquery.countdown.min.js"></script>
<script src="../../assets/vendor/dropzone/dropzone.min.js"></script>
<script src="../../assets/vendor/easy-pie-chart/jquery.easypiechart.min.js"></script>
<script src="../../assets/vendor/fancybox/js/jquery.fancybox.min.js"></script>
<script src="../../assets/vendor/flatpickr/flatpickr.min.js"></script>
<script src="../../assets/vendor/flip/flip.min.js"></script>
<script src="../../assets/vendor/footer-reveal/footer-reveal.min.js"></script>
<script src="../../assets/vendor/gradientify/jquery.gradientify.min.js"></script>
<script src="../../assets/vendor/headroom/headroom.min.js"></script>
<script src="../../assets/vendor/headroom/jquery.headroom.min.js"></script>
<script src="../../assets/vendor/input-mask/input-mask.min.js"></script>
<script src="../../assets/vendor/instafeed/instafeed.js"></script>
<script src="../../assets/vendor/milestone-counter/jquery.countTo.js"></script>
<script src="../../assets/vendor/nouislider/js/nouislider.min.js"></script>
<script src="../../assets/vendor/paraxify/paraxify.min.js"></script>
<script src="../../assets/vendor/select2/js/select2.min.js"></script>
<script src="../../assets/vendor/sticky-kit/sticky-kit.min.js"></script>
<script src="../../assets/vendor/swiper/js/swiper.min.js"></script>
<script src="../../assets/vendor/textarea-autosize/autosize.min.js"></script>
<script src="../../assets/vendor/typeahead/typeahead.bundle.min.js"></script>
<script src="../../assets/vendor/typed/typed.min.js"></script>
<script src="../../assets/vendor/vide/vide.min.js"></script>
<script src="../../assets/vendor/viewport-checker/viewportchecker.min.js"></script>
<script src="../../assets/vendor/wow/wow.min.js"></script>

<!-- Isotope -->
<script src="../../assets/vendor/isotope/isotope.min.js"></script>
<script src="../../assets/vendor/imagesloaded/imagesloaded.pkgd.min.js"></script>



<!-- App JS -->
<script src="../../assets/js/boomerang.min.js"></script>

</body>
</html>