config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  
  get 'profil', to: 'users#show', as: 'my_profil'
  
  get 'items/:id', to: 'items#show', as: 'item'
  
  post 'cart/add/:id', to: 'carts#add_to_cart', as: 'add_item_to_cart'
  post 'cart/delete/:id', to: 'carts#delete_of_cart', as: 'delete_item_of_cart'
  post 'cart/payment', to: 'carts#payment', as: 'cart_payment'
  post 'merci', to: 'orders#merci', as: 'merci'
  get 'cart', to: 'carts#show', as: 'cart_list'

  # get 'users/edit', to: 'users#edit', as: 'user_edit'

  post 'order/add/:id', to: 'orders#add_to_order', as: 'add_cart_to_order'
  post 'order/delete/:id', to: 'orders#delete_order', as: 'delete_order'
  get 'orders/new', to: 'orders#new', as: 'new_order'
  get 'orders/:id', to: 'orders#show', as: 'order'










  # edit_user_registration_path 	GET 	/users/edit(.:format) 	

  resources :orders
  resources :carts

  devise_for :users , except: [:edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :added_items, through: :cart_items
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  # !!!! Genéré par Scaffold !!!

  before_action :authenticate_user! 
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    if current_user.cart.added_items.length > 0
      @items_of_users_cart = current_user.cart.added_items.all
    else
      @items_of_users_cart = nil
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

# GET /carts/payment
  def payment
    # @test = Item.all
    # Code stripe qui suit non nécessaire, ça se passe dans la view
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_to_cart
    the_item = Item.find_by(params.permit(:id))
    if current_user.cart.added_items.length > 0
      unless current_user.cart.added_items.find_by_id(the_item)
          current_user.cart.added_items.push(the_item)
          redirect_to cart_list_path
      else
        #Mettre alarm
      end
    else
      current_user.cart.added_items.push(the_item)
      redirect_to cart_list_path
    end
    # TODO : rajouter alarm
  end

  def merci
  end

  def delete_of_cart
    the_item = Item.find_by(params.permit(:id))
    current_user.cart.added_items.delete(the_item)
    redirect_to cart_path(current_user.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
	def check_total
		return current_user.cart.added_items.inject(0) { |sum, n| sum + n.price }
	end
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/merci.html.erb
<h1>merci pour votre achat</h1>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/payment.html.erb
<section class="slice-xs sct-color-2 border-bottom">
    <div class="container container-sm">
        <div class="row cols-delimited">
            <div class="col-3">
                <div class="icon-block icon-block--style-1-v5 text-center">
                    <div class="block-icon mb-0">
                        <i class="icon-hotel-restaurant-105"></i>
                    </div>
                    <div class="block-content d-none d-md-block">
                        <h3 class="heading heading-sm strong-300 c-gray-light text-capitalize">1. Shopping bag</h3>
                    </div>
                </div>
            </div>

            <div class="col-3">
                <div class="icon-block icon-block--style-1-v5 text-center">
                    <div class="block-icon mb-0">
                        <i class="icon-finance-067"></i>
                    </div>
                    <div class="block-content d-none d-md-block">
                        <h3 class="heading heading-sm strong-300 c-gray-light text-capitalize">1. Customer info</h3>
                    </div>
                </div>
            </div>

            <div class="col-3">
                <div class="icon-block icon-block--style-1-v5 text-center">
                    <div class="block-icon  mb-0">
                        <i class="icon-finance-018"></i>
                    </div>
                    <div class="block-content d-none d-md-block">
                        <h3 class="heading heading-sm strong-300 c-gray-light text-capitalize">2. Shipping info</h3>
                    </div>
                </div>
            </div>

            <div class="col-3">
                <div class="icon-block icon-block--style-1-v5 text-center active">
                    <div class="block-icon c-gray-light mb-0">
                        <i class="icon-finance-059"></i>
                    </div>
                    <div class="block-content d-none d-md-block">
                        <h3 class="heading heading-sm strong-300 c-gray-light text-capitalize">3. Payment method</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="slice sct-color-1">
    <div class="container">
        <div class="row row-no-padding cols-xs-space cols-sm-space cols-md-space">
            <div class="col-lg-7">
                <form class="form-default mt-4" data-toggle="validator" role="form">
                    <h3 class="heading heading-3 strong-400 mb-4">Payment method</h3>

                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-lg-8">
                                    <div class="radio">
                                        <input type="radio" name="radioPayment" id="radioPayment_1" checked>
                                        <label class="heading heading-6 strong-600" for="radioPayment_1">Credit Card</label>
                                    </div>

                                    <p class="c-gray-light mt-2 pl-4">
                                        Safe money transfer using your bank account. We support Mastercard, Visa, Maestro and Skrill.
                                    </p>
                                </div>

                                <div class="col-lg-4 text-lg-right">
                                    <%= image_tag(image_path('icons/cards/mastercard.png')) %>
                                    <%= image_tag(image_path('icons/cards/visa.png')) %>
                                    <%= image_tag(image_path('icons/cards/skrill.png')) %>
                                </div>
                            </div>

                            <div class="row mt-3">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="control-label">Card number</label>
                                        <div class="input-group input-group--style-1">
                                            <input type="text" class="form-control form-control-lg input-mask" data-mask="0000 0000 0000 0000" placeholder="0000 0000 0000 0000">
                                            <span class="input-group-addon">
                                                <i class="ion-card"></i>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">Name on card</label>
                                        <input type="text" class="form-control form-control-lg">
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="control-label">Expiry date</label>
                                        <input type="text" class="form-control form-control-lg input-mask" data-mask="00/00" placeholder="MM/YY">
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="control-label">CVV code</label>
                                        <div class="input-group input-group--style-1">
                                            <input type="text" class="form-control form-control-lg input-mask" data-mask="000">
                                            <span class="input-group-addon" data-toggle="popover" title="What is a CVV code?" data-content="It is a three digit code that can be found only on the back of your card. Be carefull so no one sees it.">
                                                <i class="ion-help-circled"></i>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row align-items-center pt-5">
                      <div class="col-6">
                          <a href="<%= root_path %>" class="link link--style-3">
                              <i class="ion-android-arrow-back" ></i>
                              Return to shop
                          </a>
                      </div>
                        <div class="col-6 text-right">
                            <button type="submit" class="btn btn-styled btn-base-1">Complete order</button>
                        </div>
                    </div>
                </form>
            </div>

            <div class="col-lg-4 ml-lg-auto">
                <div class="card">
                    <div class="card-title">
                        <div class="row align-items-center">
                            <div class="col-6">
                                <h3 class="heading heading-3 strong-400 mb-0">
                                    <span>Summary</span>
                                </h3>
                            </div>
                        </div>
                    </div>

                    <div class="card-body">
                        <table class="table-cart table-cart-review">
                            <thead>
                                <tr>
                                    <th class="product-name">Product</th>
                                    <th class="product-total text-right">Total</th>
                                </tr>
                            </thead>
                            <tbody>
                              <% @test.each do |item| %>

                                <tr class="cart_item">
                                    <td class="product-name">
                                        <%= item.title %>
                                        <strong class="product-quantity">× 1</strong>
                                    </td>
                                    <td class="product-total text-right">
                                        <span><%= item.price %></span>
                                    </td>
                                </tr>
                                <% end %>

                            </tbody>

                            <tfoot>
                                <tr class="cart-subtotal no-border">

                                <tr class="cart-total">
                                    <th><span class="strong-600">Total</span></th>
                                    <td class="text-right">
                                        <strong><span> test</span></strong>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                      </div>
                  </div>

                  <div class="sidebar sidebar--style-2 mt-5">
                      <div class="sidebar-object mb-0">
                          <div class="icon-block icon-block--style-1-v2">
                              <div class="block-icon block-icon-sm pt-2">
                                  <i class="icon-transport-025"></i>
                              </div>
                              <div class="block-content">
                                  <h3 class="heading heading-6 strong-500">Fast shipping from 24 to 38 hours</h3>
                                  <p>
                                      We will send you your cat by howl don't worry.... except if the howl is hungry!
                                  </p>
                              </div>
                          </div>

                          <div class="icon-block icon-block--style-1-v2 mt-5">
                              <div class="block-icon block-icon-sm pt-2">
                                  <i class="icon-finance-114"></i>
                              </div>
                              <div class="block-content">
                                  <h3 class="heading heading-6 strong-500">30 days money back guarantee</h3>
                                  <p>
                                      You want your money back? You don't like your new cat? Are you serious? But....it's a cat! everybody loves cats !
                                  </p>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </section>

app/views/carts/show.html.erb
<section class="slice-xs sct-color-2 border-bottom">
    <div class="container container-sm">
        <div class="row cols-delimited">
            <div class="col-3">
                <div class="icon-block icon-block--style-1-v5 text-center active">
                    <div class="block-icon mb-0">
                        <i class="icon-hotel-restaurant-105"></i>
                    </div>
                    <div class="block-content d-none d-md-block">
                        <h3 class="heading heading-sm strong-300 c-gray-light text-capitalize"> Shopping Cart</h3>
                    </div>
                </div>
            </div>


        </div>
    </div>
</section>

<section class="slice sct-color-1">
    <div class="container">
        <div class="row cols-xs-space cols-sm-space cols-md-space">
            <div class="col-lg-8">
                    <div class="">
                        <div class="">
                            <% unless @items_of_users_cart == nil %>
                            <table class="table-cart border-bottom">
                                <thead>
                                    <tr>
                                        <th class="product-image"></th>
                                        <th class="product-name">Product</th>
                                        <th class="product-price d-none d-lg-table-cell">Price</th>
                                        <th class="product-remove"></th>
                                    </tr>
                                </thead>
                                <tbody>
                                <% @items_of_users_cart.each { |item| %>
                                    <tr class="cart-item">
                                        <td class="product-image">
                                            <a href="<%= item_path(item.id) %>" class="mr-5">
                                                <img src="<%= item.image_url %>">
                                            </a>
                                        </td>

                                        <td class="product-name">
                                            <span class="pr-4"><%= item.title %></span>
                                        </td>

                                        <td class="product-price d-none d-lg-table-cell">
                                            <span class="pr-4"><%= item.price %></span>
                                        </td>

                                        <td class="product-remove">
                                            <%= button_to delete_item_of_cart_path(item.id), :action =>"delete", :class => "btn btn-styled btn-block btn-warning btn-icon-left" do %>
                                                <i class="ion-trash-a"></i>
                                            <% end %>
                                        </td>
                                    </tr>
                                <% }
                                else %>
                                    <p> Votre panier est vide. </p>
                                <% end%>
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <div class="row align-items-center pt-5">
                        <div class="col-6">
                            <a href="<%= root_path %>" class="link link--style-3">
                                <i class="ion-android-arrow-back" ></i>
                                Return to shop
                            </a>
                        </div>
                        <div class="col-6 text-right">
                            <%# <button type="submit" class="btn btn-styled btn-base-1">Proceed to checkout</button> %>
                        <% unless @items_of_users_cart == nil %>
                            <%= form_tag merci_path do %>
                              <article>
                                <% if flash[:error].present? %>
                                  <div id="error_explanation">
                                    <p><%= flash[:error] %></p>
                                  </div>
                                <% end %>

                              </article>
                              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                                      data-description="Paiement trop cool"
                                      data-amount= <%=check_total * 100 %>
                                      data-currency="eur"
                                      data-email="<%= current_user.email %>"
                                      data-locale="auto">
                                </script>
                        <% end 
                        end%>

                        </div>
                    </div>

            </div>


            <div class="col-lg-4 ml-lg-auto">
                <div class="card">
                    <div class="card-title">
                        <div class="row align-items-center">
                            <div class="col-6">
                                <h3 class="heading heading-3 strong-400 mb-0">
                                    <span>Summary</span>
                                </h3>
                            </div>
                            <div class="col-6 text-right">
                                <span class="badge badge-md badge-pill bg-blue"><%= @items_of_users_cart == nil ? 0 : @items_of_users_cart.length %> items</span>
                            </div>
                        </div>
                    </div>

                    <div class="card-body">
                        <table class="table-cart table-cart-review">
                            <thead>
                                <tr>
                                    <th class="product-name">Product</th>
                                    <th class="product-total text-right">Total</th>
                                </tr>
                            </thead>
                            <tbody>
                            <% unless @items_of_users_cart == nil
							 @items_of_users_cart.each { |item| %>
                                <tr class="cart_item">
                                    <td class="product-name">
                                        <%= item.title %>
                                        <strong class="product-quantity">× 1</strong>
                                    </td>
                                    <td class="product-total text-right">
                                        <span><%= item.price %></span>
                                    </td>
                                </tr>

                                <% }
                                end %>
                            </tbody>

                            <tfoot>
                                <tr class="cart-subtotal no-border">

                                <tr class="cart-total">
                                    <th><span class="strong-600">Total</span></th>
                                    <td class="text-right">
                                        <strong><span><%= check_total %></span></strong>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>

                <div class="sidebar sidebar--style-2 mt-5">
                    <div class="sidebar-object mb-0">
                        <div class="icon-block icon-block--style-1-v2">
                            <div class="block-icon block-icon-sm pt-2">
                                <i class="icon-transport-025"></i>
                            </div>
                            <div class="block-content">
                                <h3 class="heading heading-6 strong-500">Fast shipping from 24 to 38 hours</h3>
                                <p>
                                    We will send you your cat by howl don't worry.... except if the howl is hungry!
                                </p>
                            </div>
                        </div>

                        <div class="icon-block icon-block--style-1-v2 mt-5">
                            <div class="block-icon block-icon-sm pt-2">
                                <i class="icon-finance-114"></i>
                            </div>
                            <div class="block-content">
                                <h3 class="heading heading-6 strong-500">30 days money back guarantee</h3>
                                <p>
                                    You want your money back? You don't like your new cat? Are you serious? But....it's a cat! everybody loves cats !
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>