config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  
  get 'profil', to: 'users#show', as: 'my_profil'
  
  get 'items/:id', to: 'items#show', as: 'item'
  
  post 'cart/add/:id', to: 'carts#add_to_cart', as: 'add_item_to_cart'
  post 'cart/delete/:id', to: 'carts#delete_of_cart', as: 'delete_item_of_cart'
  post 'cart/payment', to: 'carts#payment', as: 'cart_payment'
  post 'merci', to: 'orders#merci', as: 'merci'
  get 'cart', to: 'carts#show', as: 'cart_list'

  # get 'users/edit', to: 'users#edit', as: 'user_edit'

  post 'order/add/:id', to: 'orders#add_to_order', as: 'add_cart_to_order'
  post 'order/delete/:id', to: 'orders#delete_order', as: 'delete_order'
  get 'orders/new', to: 'orders#new', as: 'new_order'
  get 'orders/:id', to: 'orders#show', as: 'order'










  # edit_user_registration_path 	GET 	/users/edit(.:format) 	

  resources :orders
  resources :carts

  devise_for :users , except: [:edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  validates :title, uniqueness: true
  validates :price, numericality: true
  validates :title, :price, :description, :image_url, presence: true

  has_many :cart_items, foreign_key: :added_item_id
  has_many :carts, through: :cart_items

  has_many :users, through: :carts

  has_many :item_orders, foreign_key: :purchased_item_id
  has_many :orders, through: :item_orders

  has_many :users, through: :orders
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  	# Je récupère la liste de tous les items
  	@list_items = Item.all
  	# Sur la page index, je vais faire un each pour afficher chaque item
  end

  def show
  	@this_item = Item.find_by(params.permit(:id))
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<section class="slice-lg page-title bg-minimalist">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="text-center">
                    <h3 class="heading heading-1 strong-400 text-capitalize mb-2">
                        <span>Photos de chatons</span>
                    </h3>
                </div>
                <!-- Fluid text paragraph -->
                <div class="fluid-paragraph text-center mt-4">
                    <p class="">
                        Découvrez des photos de superbes chatons et achetez celles que vous préférez !
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="slice sct-color-1" id="sct_products">
<% if @list_items.length > 0 %>
	<div class="container shop-default shop-minimalist">
		<div class="row-wrapper">
			<div class="row cols-xs-space cols-sm-space cols-md-space">
			<% @list_items.each do |item| %>
				<div class="col-lg-3 col-md-6">
        			<div class="block product no-border z-depth-2--hover">
        			    <!-- Image produit -->
        			    <div class="block-image">
        			        <a href="<%=item_path(item.id)%>">
        			            <img alt="<%= item.title %>" src="<%=item.image_url%>" >
        			        </a>
        			    </div>
						<!-- Informations produits -->
		    	    	<div class="block-body px-0 text-center">
		    	    	    <h3 class="heading heading-6 strong-500 text-capitalize">
		    	    	        <a href=" <%=item_path(item.id)%> ">
		    	    	            <%=item.title %>
		    	    	        </a>
		    	    	    </h3>
		    	    	    <div class="price-wrapper">
		    	    	        <span class="price heading-6 c-gray-light strong-400"><span class="price-value"><%= item.price %> €</span></span>
		    	    	    </div>
                            <% if user_signed_in? %>
                            <div class="d-table product-quantity width-100 mt-3">
                                <div class="d-table-cell">
                                    <!-- Add to cart button -->
                                    <%= button_to add_item_to_cart_path(item.id), :class => "btn btn-styled btn-block btn-base-1 btn-icon-left" do %>
                                            <i class="icon ion-bag"></i> Ajouter au panier
                                    <% end %>
                                </div>
                            </div>
                            <% end %>
		    	    	</div>
		    	    </div>
        		</div>
    		<% end %>
    		</div>
    	</div>
	</div>
<% else %>
	<p> Il n'y a pas encore d'item. Revenez bientôt ! </p>
<% end %>

	</div>
</section>

app/views/items/show.html.erb
<section class="slice sct-color-1">
	<div class="container">
		<!-- Product gallery and Description -->
		<div class="row cols-xs-space cols-sm-space cols-md-space">
		    <div class="col-lg-6">
		    	<div class="gallery-container">
		    		<div id="slideshow" class="gallery-top no-padding bg-transparent">
		    			<div class="desoslide-wrapper">
		    				<img class="img-responsive" src="<%= @this_item.image_url %>" alt="<%= @this_item.title %>" style="opacity: 1;">
		    			</div>
		    		</div>
		    		
		    	</div>
		    </div>
		    <div class="col-lg-6">
		    	<div class="px-2">
		    		<!-- Product description -->
					<div class="product-description-wrapper px-1">
						<!-- Product title -->
						<h2 class="product-title">
							<%= @this_item.title %>
						</h2>
						<hr>
						<!-- Product description -->
						<div class="product-short-text mt-3">
						    <h3 class="heading heading-xs strong-500 text-uppercase">
						        Description:
						    </h3>
						    <p><%= @this_item.description %></p>
						</div>
						<hr>
						<span class="d-block heading-xs text-uppercase c-gray-light mt-4">Prix :</span>
						<h2 class="heading heading-2 strong-600 c-base-1 mt-2"> <%= @this_item.price %> </h2>
						<!-- Add to cart button if user is connected :-->
						<% if user_signed_in? %>
						<div class="d-table product-quantity width-100 mt-3">
							<div class="d-table-cell">
								<!-- Add to cart button -->
								<%= button_to add_item_to_cart_path(@this_item.id), :class => "btn btn-styled btn-block btn-base-1 btn-icon-left" do %>
  										<i class="icon ion-bag"></i> Ajouter au panier
								<% end %>
							</div>
						</div>
						<% end %>
					</div>
		    	</div>	    	
		    </div>
		</div>
	</div>
</section>