config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  
  get 'profil', to: 'users#show', as: 'my_profil'
  
  get 'items/:id', to: 'items#show', as: 'item'
  
  post 'cart/add/:id', to: 'carts#add_to_cart', as: 'add_item_to_cart'
  post 'cart/delete/:id', to: 'carts#delete_of_cart', as: 'delete_item_of_cart'
  post 'cart/payment', to: 'carts#payment', as: 'cart_payment'
  post 'merci', to: 'orders#merci', as: 'merci'
  get 'cart', to: 'carts#show', as: 'cart_list'

  # get 'users/edit', to: 'users#edit', as: 'user_edit'

  post 'order/add/:id', to: 'orders#add_to_order', as: 'add_cart_to_order'
  post 'order/delete/:id', to: 'orders#delete_order', as: 'delete_order'
  get 'orders/new', to: 'orders#new', as: 'new_order'
  get 'orders/:id', to: 'orders#show', as: 'order'










  # edit_user_registration_path 	GET 	/users/edit(.:format) 	

  resources :orders
  resources :carts

  devise_for :users , except: [:edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<footer id="footer" class="footer">
<div class="footer-top">
<div class="container">
<div class="row cols-xs-space cols-sm-space cols-md-space">
<div class="col-lg-5">
<div class="col">
      <img src="<%= image_path('logo/logo-1-c.png') %>">
      
    <span class="clearfix"></span>
    <span class="heading heading-sm c-gray-light strong-400">One template. Infinite solutions.</span>
    <p class="mt-3">
        All the components included in Boomerang are built to the same level of quality as Bootstrap and highlighted with several example pages.
    </p>

    <div class="copyright mt-4">
        <p>
            Copyright &copy; 2018                                <a href="https://webpixels.io" target="_blank">
                <strong>Webpixels</strong>
            </a> -
            All rights reserved
        </p>
    </div>
</div>
</div>

<div class="col-lg-2">
<div class="col">
   <h4 class="heading heading-xs strong-600 text-uppercase mb-1">
       Support
   </h4>

   <ul class="footer-links">
        <li><a href="#" title="Help center">Help center</a></li>
        <li><a href="#" title="Discussions">Discussions</a></li>
        <li><a href="#" title="Contact support">Contact</a></li>
        <li><a href="#" title="Blog">Blog</a></li>
        <li><a href="#" title="Jobs">FAQ</a></li>
    </ul>
 </div>
</div>

<div class="col-lg-2">
<div class="col">
    <h4 class="heading heading-xs strong-600 text-uppercase mb-1">
        Company
    </h4>

    <ul class="footer-links">
         <li>
             <a href="#" title="Home">
                 Home
             </a>
         </li>
         <li>
             <a href="#" title="About us">
                 About us
             </a>
         </li>
         <li>
             <a href="#" title="Services">
                 Services
             </a>
         </li>
         <li>
             <a href="#" title="Blog">
                 Blog
             </a>
         </li>
         <li>
             <a href="#" title="Contact">
                 Contact
             </a>
         </li>
     </ul>
</div>
</div>

<div class="col-lg-3">
<div class="col">
    <h4 class="heading heading-xs strong-600 text-uppercase mb-1">
        Get in touch
    </h4>

    <ul class="social-media social-media--style-1-v4">
        <li>
            <a href="#" class="facebook" target="_blank" data-toggle="tooltip" data-original-title="Facebook">
                <i class="fa fa-facebook"></i>
            </a>
        </li>
        <li>
            <a href="#" class="instagram" target="_blank" data-toggle="tooltip" data-original-title="Instagram">
                <i class="fa fa-instagram"></i>
            </a>
        </li>
        <li>
            <a href="#" class="dribbble" target="_blank" data-toggle="tooltip" data-original-title="Dribbble">
                <i class="fa fa-dribbble"></i>
            </a>
        </li>
        <li>
            <a href="#" class="dribbble" target="_blank" data-toggle="tooltip" data-original-title="Github">
                <i class="fa fa-github"></i>
            </a>
        </li>
    </ul>
</div>
</div>
</div>
</div>
</div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar--bold navbar--style-2 navbar-light bg-default  navbar--bb-1px" fixed-top">
 <a class="navbar-brand" href="<%= root_path %>">Mon chat à Moi</a>
 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
   <span class="navbar-toggler-icon"></span>
 </button>

 <div class="collapse navbar-collapse" id="navbarsExampleDefault">
   <ul class="navbar-nav mr-auto">
     <li class="nav-item active">
       <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
     </li>

   </ul>
     <ul class="nav navbar-nav navbar">
       <% if user_signed_in? %>

         <li>
           <a class="nav-link"><%= "Bonjour"+" "+ current_user.firstname%></a>
         </li>

                   <li class="nav-item">
            <a class="nav-link" href="<%= my_profil_path %>">Profile</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="<%= cart_list_path %>">Panier</a>
          </li>

          <li class="nav-item">
            <a class=<%= link_to "Log Out", destroy_user_session_path, method: :delete %>
          </li>

       <% else %>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_user_session_path %>">Log in</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_user_registration_path %>">Sign up</a>
          </li>
      <% end %>


   </ul>
 </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boutique</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Fonts -->
<link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700,800|Roboto:400,500,700" rel="stylesheet">
<link href="<%= image_path('favicon.png') %>" rel="icon" type="image/png">

  </head>

  <body>

    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>